id: AF3214233
title: Method of Confession Based on the Four Powers
type: translation
pechas:
- I12B115B4
- I6F741C01
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:57:50.464237
  last_modified_at: 2023-01-04 12:57:50.464258
  collections:
  - Lobzang Chökyi Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  I12B115B4/F23B: 2F4D
  I6F741C01/FE07: 2F4D
